### ISSUE TITLE
brew install watchman is installing an invalid version

### ISSUE THREAD

**Issue by lilshebeary** [facebook/watchman#915]
brew install watchman is installing an invalid version

Warning: Problem checking watchman version. Invalid Version: 2021.06.07.00.

Warning: watchman 2021.06.07.00 is already installed and up-to-date.
To reinstall 2021.06.07.00, run:
  brew reinstall watchman

**Comment by dtrodrigues** [comment]
This would be a homebrew packaging issue, but I'm unable to reproduce it. Can you file an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose please?

**Comment by lilshebeary** [comment]
I could, I just fixed this, I think yesterday with some setup directions in native class that I forgot to set up, I want to post them here but I don't know if this is ok to do, but just globally setting up npm and also I found this online 

sudo chmod 2777 /usr/local/var/run/watchman 

because after I set up I was also having permissions issues. I am new to programming so all of this is very confusing.
I am having a hard time setting up a new project but I will wait to see if I can fix it.
Thank you for getting back to me.

**Comment by VictorioMolina** [comment]
same problem here.

**Comment by abosaiftaha** [comment]
same problem here

**Comment by edagnin** [comment]
Still having this issue on Mac.

Tried with both Homebrew and MacPorts and same issue with both.

Versions of watchman (at time of installation):

- MacPorts: `2022.01.17.00`
- Homebrew: '2022.02.14.00'

Terminal output (Homebrew installation):

>  ✖  Watchman - Used for watching changes in the filesystem when in development mode
>    - Version found: 2022.02.14.00
>    - Version supported: 4.x

Terminal output (MacPorts installation):

> ✖ Watchman - Used for watching changes in the filesystem when in development mode
>  - Version found: 0.0.0
>  - Version supported: 4.x

Both Homebrew and MacPorts are of the recommended installation methods for watchman according to the installation page: [watchman installation](https://facebook.github.io/watchman/docs/install.html)

I know it was suggested to log a bug with Homebrew, but I don't believe it's a Homebrew issue when both Homebrew and MacPorts are producing a similar issue.

**Comment by greatshah222** [comment]
still have the same issue. did anyone yet find the solution?

**Comment by 94Rabbit** [comment]
> still have the same issue. did anyone yet find the solution?

same case! did you find the solution?

**Comment by emplu-de** [comment]
Hello??? same here

**Comment by robhogan** [comment]
> ✖ Watchman - Used for watching changes in the filesystem when in development mode
> 
> Version found: 2022.02.14.00
> Version supported: 4.x

This looks like the output of `react-native doctor`, right? This is a misleading warning caused by `doctor` not understanding Watchman's newer version format - the date-style versions are all newer than 4.9, and all supported by React Native / Metro. The warning was fixed in https://github.com/react-native-community/cli/pull/1700, but can be safely ignored.
